#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     not POSIX compliant, but you have some other compliant shell such as
#     bash, ksh, or zsh, then change the shebang line to use that shell.
#
# (2) Put the GRADLE_HOME environment variable in your environment.
#
# (3) You have a JAR file in the GRADLE_HOME/wrapper directory named
#     gradle-wrapper.jar
#
# (4) You added a GRADLE_HOME environment variable in your environment.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}; [ -h "$app_path" ]
do
    app_path=$(expr "$app_path" : '.*->\(.*\)$')
    [ -z "$app_path" ] && app_path=.
    continue
done

cd "$(dirname "$app_path")" || exit

APP_HOME=$(pwd -P) || exit
CD_HOME=$PWD

echo $APP_HOME

# Start wrapper
exec "$APP_HOME/gradle/wrapper/gradlew.sh" "$@"
